--liquibase formatted sql

--changeset id:16 author:umnick
INSERT INTO DELIVERY_WINDOW (ID, DAY_OF_WEEK, FROM_TIME, TO_TIME, ACTIVE) VALUES (595, 'MONDAY', '10:00', '12:00', true);
INSERT INTO DELIVERY_WINDOW (ID, DAY_OF_WEEK, FROM_TIME, TO_TIME, ACTIVE) VALUES (596, 'MONDAY', '12:00', '14:00', false);
INSERT INTO DELIVERY_WINDOW (ID, DAY_OF_WEEK, FROM_TIME, TO_TIME, ACTIVE) VALUES (597, 'TUESDAY', '12:00', '14:00', true);