--liquibase formatted sql

--changeset id:10 author:umnick
INSERT INTO DISH_ITEM (ID, QUANTITY, INGREDIENT_ID, DISH_ID) VALUES (1, 0.3, 1, 1);
INSERT INTO DISH_ITEM (ID, QUANTITY, INGREDIENT_ID, DISH_ID) VALUES (2, 0.1, 2, 2);
INSERT INTO DISH_ITEM (ID, QUANTITY, INGREDIENT_ID, DISH_ID) VALUES (3, 0.03, 3, 2);
INSERT INTO DISH_ITEM (ID, QUANTITY, INGREDIENT_ID, DISH_ID) VALUES (4, 0.03, 4, 2);
INSERT INTO DISH_ITEM (ID, QUANTITY, INGREDIENT_ID, DISH_ID) VALUES (5, 0.015, 5, 2);