--liquibase formatted sql

--changeset id:11 author:umnick
INSERT INTO INGREDIENT (ID, CARBS, FATS, KCAL, NAME, PIC, PROTEIN) VALUES (1, 0, 33.3, 357, 'свинина', null, 14.3);
INSERT INTO INGREDIENT (ID, CARBS, FATS, KCAL, NAME, PIC, PROTEIN) VALUES (2, 19, 0.47, 102, 'томатная паста', null, 4.8);
INSERT INTO INGREDIENT (ID, CARBS, FATS, KCAL, NAME, PIC, PROTEIN) VALUES (3, 8.2, 0.2, 41, 'лук', null, 1.4);
INSERT INTO INGREDIENT (ID, CARBS, FATS, KCAL, NAME, PIC, PROTEIN) VALUES (4, 5.3, 0.1, 27, 'перец сладкий', null, 1.3);
INSERT INTO INGREDIENT (ID, CARBS, FATS, KCAL, NAME, PIC, PROTEIN) VALUES (5, 6.17, 0.3, 35, 'зелень', null, 7.5);