--liquibase formatted sql

--changeset id:12 author:umnick
INSERT INTO INGREDIENT (ID, CARBS, FATS, KCAL, NAME, PIC, PROTEIN) VALUES (580, 0, 33.3, 357, 'свинина', null, 14.3);
INSERT INTO INGREDIENT (ID, CARBS, FATS, KCAL, NAME, PIC, PROTEIN) VALUES (581, 19, 0.47, 102, 'томатная паста', null, 4.8);
INSERT INTO INGREDIENT (ID, CARBS, FATS, KCAL, NAME, PIC, PROTEIN) VALUES (582, 8.2, 0.2, 41, 'лук', null, 1.4);
INSERT INTO INGREDIENT (ID, CARBS, FATS, KCAL, NAME, PIC, PROTEIN) VALUES (583, 5.3, 0.1, 27, 'перец сладкий', null, 1.3);
INSERT INTO INGREDIENT (ID, CARBS, FATS, KCAL, NAME, PIC, PROTEIN) VALUES (584, 6.17, 0.3, 35, 'зелень', null, 7.5);