--liquibase formatted sql

--changeset id:15 author:umnick
INSERT INTO MENU_DISHES (MENU_ID, DISHES_ID) VALUES (592, 585);
INSERT INTO MENU_DISHES (MENU_ID, DISHES_ID) VALUES (592, 587);
INSERT INTO MENU_DISHES (MENU_ID, DISHES_ID) VALUES (593, 585);
INSERT INTO MENU_DISHES (MENU_ID, DISHES_ID) VALUES (594, 587);